language: node_js
sudo: false
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g @angular/cli@latest

script:
  - npm install
  # headless chrome add.
  # - ng test
  # - ng e2e
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  local_dir: dist/site/
  github_token: $GITHUB_TOKEN
  on:
    branch: master